---
- name: Azure - Create infrastructure
  hosts: localhost

  tasks:

    - name: Create Virtual Network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ my_azure_resource_group }}"
        name: "{{ my_azure_vnet }}"
        address_prefixes: "{{ my_azure_vnet_cidr }}"
    
    - name: Create Subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ my_azure_resource_group }}"
        name: "{{ my_azure_subnet }}"
        address_prefix: "{{ my_azure_vnet_cidr }}"
        virtual_network: "{{ my_azure_vnet }}"
    
    - name: Create Security Group
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ my_azure_resource_group }}"
        name: "{{ my_azure_security_group }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 999
            direction: Inbound
          - name: Ansible-receptor
            protocol: Tcp
            destination_port_range: 27199
            access: Allow
            priority: 1000
            direction: Inbound
          - name: External
            protocol: Tcp
            destination_port_range:
              - 80 # HTTP
              - 443 # HTTPS
              - 5986 # WinRM
              - 3389 # RDP
            access: Allow
            priority: 1001
            direction: Inbound
          - name: Ping
            protocol: Icmp
            access: Allow
            priority: 1002
            direction: Inbound
          - name: InternalTCP
            protocol: Tcp
            destination_port_range:
              - 80 # HTTP
              - 5986 # WinRM
              - 3389 # RDP
              - 53 # DNS
              - 88 # Kerberos Authentication
              - 135 # RPC
              - 139 # Netlogon
              - 389 # LDAP
              - 445 # SMB
              - 464 # Kerberos Authentication
              - 5432 # PostgreSQL
              - 636 # LDAPS (LDAP over TLS)
              - 873 # Rsync 
              - 3268-3269 # Global Catalog 
              #- 1024-65535 # Ephemeral RPC ports
            access: Allow
            priority: 1003
            direction: Inbound
            source_address_prefix: "{{ my_azure_vnet_cidr }}"
          - name: InternalUDP
            protocol: Udp
            destination_port_range:
              - 53 # DNS
              - 88 # Kerberos Authentication
              - 123 # NTP
              - 137-138 # Netlogon 
              - 389 # LDAP 
              - 445 # SMB
              - 464 # Kerberos Authentication
              - 1024-65535 # Ephemeral RPC ports
            access: Allow
            priority: 1004
            direction: Inbound
            source_address_prefix: "{{ my_azure_vnet_cidr }}"
