---
- name: Azure - Delete infrastructure
  hosts: localhost

  tasks:
 
    - name: Delete Subnet
      azure.azcollection.azure_rm_subnet:
        resource_group: "{{ my_azure_resource_group }}"
        name: "{{ my_azure_subnet }}"
        virtual_network: "{{ my_azure_vnet }}"
        state: absent
        
    - name: Delete Virtual Network
      azure.azcollection.azure_rm_virtualnetwork:
        resource_group: "{{ my_azure_resource_group }}"
        name: "{{ my_azure_vnet }}"
        state: absent
    
    - name: Delete Network Security Group
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ my_azure_resource_group }}"
        name: "{{ my_azure_network_security_group }}"
        state: absent

    - name: Delete Application Security Group (private and public)
      with_items:
        - "{{ my_azure_public_asg }}"
        - "{{ my_azure_private_asg }}"
      azure_rm_applicationsecuritygroup:
        resource_group: "{{ my_azure_resource_group }}"
        name: "{{ item }}"
        state: absent