---
- name: Azure - Stop all Virtual Machines in a Resource Group
  hosts: localhost

  tasks:

    - name: Get facts for all virtual machines of a Resource Group
      register: r
      azure_rm_virtualmachine_info:
        resource_group: "{{ my_azure_resource_group }}"

    - name: Show list of VMs and state
      loop: "{{ r.vms }}"    
      debug:
        msg: The Virtual Machine {{ item.name }} is in state {{ item. power_state }} and will be stopped.


    - name: Stop all VMs in resource group
      loop: "{{ r.vms }}"
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ my_azure_resource_group }}"
        name: "{{ item.name }}"
        state: present
        started: false