---
- name: Azure - Create virtual machines
  hosts: localhost

  tasks:

    #- name: Get facts for a specific image
    #  azure_rm_virtualmachineimage_info:
    #    location: westeurope
    #    publisher: RedHat
    #    offer: RHEL
    #    sku: '9_2'
    #  register: wadibi
    #
    #- debug:
    #    var: wadibi.vmimages

    - name: Create NIC for Virtual Machine
      loop: "{{ my_azure_vms }}"
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ my_azure_resource_group }}"
        name: "{{ item.name }}_nic"
        public_ip_name: "{{ item.name }}_ip"
        virtual_network: "{{ my_azure_vnet }}"
        subnet: "{{ my_azure_subnet }}"
        security_group: "{{ my_azure_security_group }}"
        
    - name: Create VM
      loop: "{{ my_azure_vms }}"
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ my_azure_resource_group }}"
        name: "{{ item.name }}"
        os_type: "{{ item.ostype }}"
        vm_size: "{{ item.size }}"
        priority: "{{ item.priority }}"
        admin_username: "{{ item.username }}"
        admin_password: "{{ item.password }}"
        network_interfaces: "{{ item.name }}_nic"
        image:
          publisher: "{{ item.image.publisher }}"
          offer: "{{ item.image.offer }}"
          sku: "{{ item.image.sku }}"
          version: "{{ item.image.version }}"
#        tags:
#          blueprint: "{{ az_blueprint }}"
#          purpose: "{{ az_purpose_tag }}"
#          env: "{{ az_env_tag }}"
#          ansible_group: "{{ az_ansiblegroup_tag }}"
#          owner: "{{ az_vm_owner }}"
#          info: "This instance was built by Red Hat Product Demos"
#          Name: "{{ az_vm_name }}"